dubbo:
  registry:
    protocol: zookeeper
    address: 192.168.188.128:2181
  protocol:
    port: 20882
    name: dubbo
  application:
    name: dubbo-springboot-example
    qos-enable: true
  scan:
    basePackages: com.openlab.service
